// iOS 10.3 public ImageIO CFString exports, intersected with the ImageIO
// image's own exports. Bind exact native objects rather than symbol spellings.
// Omit the macOS-only OpenEXR keys, including the aspect-ratio symbol that
// happens to be exported by the iOS image despite its unavailable declaration.
#import <ImageIO/ImageIO.h>
#import <Foundation/Foundation+LC32.h>

#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#define LC32_IMAGEIO_STRING_CONSTANTS(X) \
    X(kCFErrorDomainCGImageMetadata) \
    X(kCGImageDestinationBackgroundColor) \
    X(kCGImageDestinationDateTime) \
    X(kCGImageDestinationEmbedThumbnail) \
    X(kCGImageDestinationImageMaxPixelSize) \
    X(kCGImageDestinationLossyCompressionQuality) \
    X(kCGImageDestinationMergeMetadata) \
    X(kCGImageDestinationMetadata) \
    X(kCGImageDestinationOptimizeColorForSharing) \
    X(kCGImageDestinationOrientation) \
    X(kCGImageMetadataEnumerateRecursively) \
    X(kCGImageMetadataNamespaceDublinCore) \
    X(kCGImageMetadataNamespaceExif) \
    X(kCGImageMetadataNamespaceExifAux) \
    X(kCGImageMetadataNamespaceExifEX) \
    X(kCGImageMetadataNamespaceIPTCCore) \
    X(kCGImageMetadataNamespacePhotoshop) \
    X(kCGImageMetadataNamespaceTIFF) \
    X(kCGImageMetadataNamespaceXMPBasic) \
    X(kCGImageMetadataNamespaceXMPRights) \
    X(kCGImageMetadataPrefixDublinCore) \
    X(kCGImageMetadataPrefixExif) \
    X(kCGImageMetadataPrefixExifAux) \
    X(kCGImageMetadataPrefixExifEX) \
    X(kCGImageMetadataPrefixIPTCCore) \
    X(kCGImageMetadataPrefixPhotoshop) \
    X(kCGImageMetadataPrefixTIFF) \
    X(kCGImageMetadataPrefixXMPBasic) \
    X(kCGImageMetadataPrefixXMPRights) \
    X(kCGImageMetadataShouldExcludeGPS) \
    X(kCGImageMetadataShouldExcludeXMP) \
    X(kCGImageProperty8BIMDictionary) \
    X(kCGImageProperty8BIMLayerNames) \
    X(kCGImageProperty8BIMVersion) \
    X(kCGImagePropertyAPNGDelayTime) \
    X(kCGImagePropertyAPNGLoopCount) \
    X(kCGImagePropertyAPNGUnclampedDelayTime) \
    X(kCGImagePropertyCIFFCameraSerialNumber) \
    X(kCGImagePropertyCIFFContinuousDrive) \
    X(kCGImagePropertyCIFFDescription) \
    X(kCGImagePropertyCIFFDictionary) \
    X(kCGImagePropertyCIFFFirmware) \
    X(kCGImagePropertyCIFFFlashExposureComp) \
    X(kCGImagePropertyCIFFFocusMode) \
    X(kCGImagePropertyCIFFImageFileName) \
    X(kCGImagePropertyCIFFImageName) \
    X(kCGImagePropertyCIFFImageSerialNumber) \
    X(kCGImagePropertyCIFFLensMaxMM) \
    X(kCGImagePropertyCIFFLensMinMM) \
    X(kCGImagePropertyCIFFLensModel) \
    X(kCGImagePropertyCIFFMeasuredEV) \
    X(kCGImagePropertyCIFFMeteringMode) \
    X(kCGImagePropertyCIFFOwnerName) \
    X(kCGImagePropertyCIFFRecordID) \
    X(kCGImagePropertyCIFFReleaseMethod) \
    X(kCGImagePropertyCIFFReleaseTiming) \
    X(kCGImagePropertyCIFFSelfTimingTime) \
    X(kCGImagePropertyCIFFShootingMode) \
    X(kCGImagePropertyCIFFWhiteBalanceIndex) \
    X(kCGImagePropertyColorModel) \
    X(kCGImagePropertyColorModelCMYK) \
    X(kCGImagePropertyColorModelGray) \
    X(kCGImagePropertyColorModelLab) \
    X(kCGImagePropertyColorModelRGB) \
    X(kCGImagePropertyDNGAsShotNeutral) \
    X(kCGImagePropertyDNGAsShotWhiteXY) \
    X(kCGImagePropertyDNGBackwardVersion) \
    X(kCGImagePropertyDNGBaselineExposure) \
    X(kCGImagePropertyDNGBaselineNoise) \
    X(kCGImagePropertyDNGBaselineSharpness) \
    X(kCGImagePropertyDNGBlackLevel) \
    X(kCGImagePropertyDNGCalibrationIlluminant1) \
    X(kCGImagePropertyDNGCalibrationIlluminant2) \
    X(kCGImagePropertyDNGCameraCalibration1) \
    X(kCGImagePropertyDNGCameraCalibration2) \
    X(kCGImagePropertyDNGCameraCalibrationSignature) \
    X(kCGImagePropertyDNGCameraSerialNumber) \
    X(kCGImagePropertyDNGColorMatrix1) \
    X(kCGImagePropertyDNGColorMatrix2) \
    X(kCGImagePropertyDNGDictionary) \
    X(kCGImagePropertyDNGFixVignetteRadial) \
    X(kCGImagePropertyDNGLensInfo) \
    X(kCGImagePropertyDNGLocalizedCameraModel) \
    X(kCGImagePropertyDNGNoiseProfile) \
    X(kCGImagePropertyDNGPrivateData) \
    X(kCGImagePropertyDNGProfileCalibrationSignature) \
    X(kCGImagePropertyDNGUniqueCameraModel) \
    X(kCGImagePropertyDNGVersion) \
    X(kCGImagePropertyDNGWarpFisheye) \
    X(kCGImagePropertyDNGWarpRectilinear) \
    X(kCGImagePropertyDNGWhiteLevel) \
    X(kCGImagePropertyDPIHeight) \
    X(kCGImagePropertyDPIWidth) \
    X(kCGImagePropertyDepth) \
    X(kCGImagePropertyExifApertureValue) \
    X(kCGImagePropertyExifAuxDictionary) \
    X(kCGImagePropertyExifAuxFirmware) \
    X(kCGImagePropertyExifAuxFlashCompensation) \
    X(kCGImagePropertyExifAuxImageNumber) \
    X(kCGImagePropertyExifAuxLensID) \
    X(kCGImagePropertyExifAuxLensInfo) \
    X(kCGImagePropertyExifAuxLensModel) \
    X(kCGImagePropertyExifAuxLensSerialNumber) \
    X(kCGImagePropertyExifAuxOwnerName) \
    X(kCGImagePropertyExifAuxSerialNumber) \
    X(kCGImagePropertyExifBodySerialNumber) \
    X(kCGImagePropertyExifBrightnessValue) \
    X(kCGImagePropertyExifCFAPattern) \
    X(kCGImagePropertyExifCameraOwnerName) \
    X(kCGImagePropertyExifColorSpace) \
    X(kCGImagePropertyExifComponentsConfiguration) \
    X(kCGImagePropertyExifCompressedBitsPerPixel) \
    X(kCGImagePropertyExifContrast) \
    X(kCGImagePropertyExifCustomRendered) \
    X(kCGImagePropertyExifDateTimeDigitized) \
    X(kCGImagePropertyExifDateTimeOriginal) \
    X(kCGImagePropertyExifDeviceSettingDescription) \
    X(kCGImagePropertyExifDictionary) \
    X(kCGImagePropertyExifDigitalZoomRatio) \
    X(kCGImagePropertyExifExposureBiasValue) \
    X(kCGImagePropertyExifExposureIndex) \
    X(kCGImagePropertyExifExposureMode) \
    X(kCGImagePropertyExifExposureProgram) \
    X(kCGImagePropertyExifExposureTime) \
    X(kCGImagePropertyExifFNumber) \
    X(kCGImagePropertyExifFileSource) \
    X(kCGImagePropertyExifFlash) \
    X(kCGImagePropertyExifFlashEnergy) \
    X(kCGImagePropertyExifFlashPixVersion) \
    X(kCGImagePropertyExifFocalLenIn35mmFilm) \
    X(kCGImagePropertyExifFocalLength) \
    X(kCGImagePropertyExifFocalPlaneResolutionUnit) \
    X(kCGImagePropertyExifFocalPlaneXResolution) \
    X(kCGImagePropertyExifFocalPlaneYResolution) \
    X(kCGImagePropertyExifGainControl) \
    X(kCGImagePropertyExifGamma) \
    X(kCGImagePropertyExifISOSpeed) \
    X(kCGImagePropertyExifISOSpeedLatitudeyyy) \
    X(kCGImagePropertyExifISOSpeedLatitudezzz) \
    X(kCGImagePropertyExifISOSpeedRatings) \
    X(kCGImagePropertyExifImageUniqueID) \
    X(kCGImagePropertyExifLensMake) \
    X(kCGImagePropertyExifLensModel) \
    X(kCGImagePropertyExifLensSerialNumber) \
    X(kCGImagePropertyExifLensSpecification) \
    X(kCGImagePropertyExifLightSource) \
    X(kCGImagePropertyExifMakerNote) \
    X(kCGImagePropertyExifMaxApertureValue) \
    X(kCGImagePropertyExifMeteringMode) \
    X(kCGImagePropertyExifOECF) \
    X(kCGImagePropertyExifPixelXDimension) \
    X(kCGImagePropertyExifPixelYDimension) \
    X(kCGImagePropertyExifRecommendedExposureIndex) \
    X(kCGImagePropertyExifRelatedSoundFile) \
    X(kCGImagePropertyExifSaturation) \
    X(kCGImagePropertyExifSceneCaptureType) \
    X(kCGImagePropertyExifSceneType) \
    X(kCGImagePropertyExifSensingMethod) \
    X(kCGImagePropertyExifSensitivityType) \
    X(kCGImagePropertyExifSharpness) \
    X(kCGImagePropertyExifShutterSpeedValue) \
    X(kCGImagePropertyExifSpatialFrequencyResponse) \
    X(kCGImagePropertyExifSpectralSensitivity) \
    X(kCGImagePropertyExifStandardOutputSensitivity) \
    X(kCGImagePropertyExifSubjectArea) \
    X(kCGImagePropertyExifSubjectDistRange) \
    X(kCGImagePropertyExifSubjectDistance) \
    X(kCGImagePropertyExifSubjectLocation) \
    X(kCGImagePropertyExifSubsecTime) \
    X(kCGImagePropertyExifSubsecTimeDigitized) \
    X(kCGImagePropertyExifSubsecTimeOrginal) \
    X(kCGImagePropertyExifSubsecTimeOriginal) \
    X(kCGImagePropertyExifUserComment) \
    X(kCGImagePropertyExifVersion) \
    X(kCGImagePropertyExifWhiteBalance) \
    X(kCGImagePropertyFileSize) \
    X(kCGImagePropertyGIFDelayTime) \
    X(kCGImagePropertyGIFDictionary) \
    X(kCGImagePropertyGIFHasGlobalColorMap) \
    X(kCGImagePropertyGIFImageColorMap) \
    X(kCGImagePropertyGIFLoopCount) \
    X(kCGImagePropertyGIFUnclampedDelayTime) \
    X(kCGImagePropertyGPSAltitude) \
    X(kCGImagePropertyGPSAltitudeRef) \
    X(kCGImagePropertyGPSAreaInformation) \
    X(kCGImagePropertyGPSDOP) \
    X(kCGImagePropertyGPSDateStamp) \
    X(kCGImagePropertyGPSDestBearing) \
    X(kCGImagePropertyGPSDestBearingRef) \
    X(kCGImagePropertyGPSDestDistance) \
    X(kCGImagePropertyGPSDestDistanceRef) \
    X(kCGImagePropertyGPSDestLatitude) \
    X(kCGImagePropertyGPSDestLatitudeRef) \
    X(kCGImagePropertyGPSDestLongitude) \
    X(kCGImagePropertyGPSDestLongitudeRef) \
    X(kCGImagePropertyGPSDictionary) \
    X(kCGImagePropertyGPSDifferental) \
    X(kCGImagePropertyGPSHPositioningError) \
    X(kCGImagePropertyGPSImgDirection) \
    X(kCGImagePropertyGPSImgDirectionRef) \
    X(kCGImagePropertyGPSLatitude) \
    X(kCGImagePropertyGPSLatitudeRef) \
    X(kCGImagePropertyGPSLongitude) \
    X(kCGImagePropertyGPSLongitudeRef) \
    X(kCGImagePropertyGPSMapDatum) \
    X(kCGImagePropertyGPSMeasureMode) \
    X(kCGImagePropertyGPSProcessingMethod) \
    X(kCGImagePropertyGPSSatellites) \
    X(kCGImagePropertyGPSSpeed) \
    X(kCGImagePropertyGPSSpeedRef) \
    X(kCGImagePropertyGPSStatus) \
    X(kCGImagePropertyGPSTimeStamp) \
    X(kCGImagePropertyGPSTrack) \
    X(kCGImagePropertyGPSTrackRef) \
    X(kCGImagePropertyGPSVersion) \
    X(kCGImagePropertyHasAlpha) \
    X(kCGImagePropertyIPTCActionAdvised) \
    X(kCGImagePropertyIPTCByline) \
    X(kCGImagePropertyIPTCBylineTitle) \
    X(kCGImagePropertyIPTCCaptionAbstract) \
    X(kCGImagePropertyIPTCCategory) \
    X(kCGImagePropertyIPTCCity) \
    X(kCGImagePropertyIPTCContact) \
    X(kCGImagePropertyIPTCContactInfoAddress) \
    X(kCGImagePropertyIPTCContactInfoCity) \
    X(kCGImagePropertyIPTCContactInfoCountry) \
    X(kCGImagePropertyIPTCContactInfoEmails) \
    X(kCGImagePropertyIPTCContactInfoPhones) \
    X(kCGImagePropertyIPTCContactInfoPostalCode) \
    X(kCGImagePropertyIPTCContactInfoStateProvince) \
    X(kCGImagePropertyIPTCContactInfoWebURLs) \
    X(kCGImagePropertyIPTCContentLocationCode) \
    X(kCGImagePropertyIPTCContentLocationName) \
    X(kCGImagePropertyIPTCCopyrightNotice) \
    X(kCGImagePropertyIPTCCountryPrimaryLocationCode) \
    X(kCGImagePropertyIPTCCountryPrimaryLocationName) \
    X(kCGImagePropertyIPTCCreatorContactInfo) \
    X(kCGImagePropertyIPTCCredit) \
    X(kCGImagePropertyIPTCDateCreated) \
    X(kCGImagePropertyIPTCDictionary) \
    X(kCGImagePropertyIPTCDigitalCreationDate) \
    X(kCGImagePropertyIPTCDigitalCreationTime) \
    X(kCGImagePropertyIPTCEditStatus) \
    X(kCGImagePropertyIPTCEditorialUpdate) \
    X(kCGImagePropertyIPTCExpirationDate) \
    X(kCGImagePropertyIPTCExpirationTime) \
    X(kCGImagePropertyIPTCFixtureIdentifier) \
    X(kCGImagePropertyIPTCHeadline) \
    X(kCGImagePropertyIPTCImageOrientation) \
    X(kCGImagePropertyIPTCImageType) \
    X(kCGImagePropertyIPTCKeywords) \
    X(kCGImagePropertyIPTCLanguageIdentifier) \
    X(kCGImagePropertyIPTCObjectAttributeReference) \
    X(kCGImagePropertyIPTCObjectCycle) \
    X(kCGImagePropertyIPTCObjectName) \
    X(kCGImagePropertyIPTCObjectTypeReference) \
    X(kCGImagePropertyIPTCOriginalTransmissionReference) \
    X(kCGImagePropertyIPTCOriginatingProgram) \
    X(kCGImagePropertyIPTCProgramVersion) \
    X(kCGImagePropertyIPTCProvinceState) \
    X(kCGImagePropertyIPTCReferenceDate) \
    X(kCGImagePropertyIPTCReferenceNumber) \
    X(kCGImagePropertyIPTCReferenceService) \
    X(kCGImagePropertyIPTCReleaseDate) \
    X(kCGImagePropertyIPTCReleaseTime) \
    X(kCGImagePropertyIPTCRightsUsageTerms) \
    X(kCGImagePropertyIPTCScene) \
    X(kCGImagePropertyIPTCSource) \
    X(kCGImagePropertyIPTCSpecialInstructions) \
    X(kCGImagePropertyIPTCStarRating) \
    X(kCGImagePropertyIPTCSubLocation) \
    X(kCGImagePropertyIPTCSubjectReference) \
    X(kCGImagePropertyIPTCSupplementalCategory) \
    X(kCGImagePropertyIPTCTimeCreated) \
    X(kCGImagePropertyIPTCUrgency) \
    X(kCGImagePropertyIPTCWriterEditor) \
    X(kCGImagePropertyIsFloat) \
    X(kCGImagePropertyIsIndexed) \
    X(kCGImagePropertyJFIFDensityUnit) \
    X(kCGImagePropertyJFIFDictionary) \
    X(kCGImagePropertyJFIFIsProgressive) \
    X(kCGImagePropertyJFIFVersion) \
    X(kCGImagePropertyJFIFXDensity) \
    X(kCGImagePropertyJFIFYDensity) \
    X(kCGImagePropertyMakerAppleDictionary) \
    X(kCGImagePropertyMakerCanonAspectRatioInfo) \
    X(kCGImagePropertyMakerCanonCameraSerialNumber) \
    X(kCGImagePropertyMakerCanonContinuousDrive) \
    X(kCGImagePropertyMakerCanonDictionary) \
    X(kCGImagePropertyMakerCanonFirmware) \
    X(kCGImagePropertyMakerCanonFlashExposureComp) \
    X(kCGImagePropertyMakerCanonImageSerialNumber) \
    X(kCGImagePropertyMakerCanonLensModel) \
    X(kCGImagePropertyMakerCanonOwnerName) \
    X(kCGImagePropertyMakerFujiDictionary) \
    X(kCGImagePropertyMakerMinoltaDictionary) \
    X(kCGImagePropertyMakerNikonCameraSerialNumber) \
    X(kCGImagePropertyMakerNikonColorMode) \
    X(kCGImagePropertyMakerNikonDictionary) \
    X(kCGImagePropertyMakerNikonDigitalZoom) \
    X(kCGImagePropertyMakerNikonFlashExposureComp) \
    X(kCGImagePropertyMakerNikonFlashSetting) \
    X(kCGImagePropertyMakerNikonFocusDistance) \
    X(kCGImagePropertyMakerNikonFocusMode) \
    X(kCGImagePropertyMakerNikonISOSelection) \
    X(kCGImagePropertyMakerNikonISOSetting) \
    X(kCGImagePropertyMakerNikonImageAdjustment) \
    X(kCGImagePropertyMakerNikonLensAdapter) \
    X(kCGImagePropertyMakerNikonLensInfo) \
    X(kCGImagePropertyMakerNikonLensType) \
    X(kCGImagePropertyMakerNikonQuality) \
    X(kCGImagePropertyMakerNikonSharpenMode) \
    X(kCGImagePropertyMakerNikonShootingMode) \
    X(kCGImagePropertyMakerNikonShutterCount) \
    X(kCGImagePropertyMakerNikonWhiteBalanceMode) \
    X(kCGImagePropertyMakerOlympusDictionary) \
    X(kCGImagePropertyMakerPentaxDictionary) \
    X(kCGImagePropertyOrientation) \
    X(kCGImagePropertyPNGAuthor) \
    X(kCGImagePropertyPNGChromaticities) \
    X(kCGImagePropertyPNGCompressionFilter) \
    X(kCGImagePropertyPNGCopyright) \
    X(kCGImagePropertyPNGCreationTime) \
    X(kCGImagePropertyPNGDescription) \
    X(kCGImagePropertyPNGDictionary) \
    X(kCGImagePropertyPNGGamma) \
    X(kCGImagePropertyPNGInterlaceType) \
    X(kCGImagePropertyPNGModificationTime) \
    X(kCGImagePropertyPNGSoftware) \
    X(kCGImagePropertyPNGTitle) \
    X(kCGImagePropertyPNGXPixelsPerMeter) \
    X(kCGImagePropertyPNGYPixelsPerMeter) \
    X(kCGImagePropertyPNGsRGBIntent) \
    X(kCGImagePropertyPixelHeight) \
    X(kCGImagePropertyPixelWidth) \
    X(kCGImagePropertyProfileName) \
    X(kCGImagePropertyRawDictionary) \
    X(kCGImagePropertyTIFFArtist) \
    X(kCGImagePropertyTIFFCompression) \
    X(kCGImagePropertyTIFFCopyright) \
    X(kCGImagePropertyTIFFDateTime) \
    X(kCGImagePropertyTIFFDictionary) \
    X(kCGImagePropertyTIFFDocumentName) \
    X(kCGImagePropertyTIFFHostComputer) \
    X(kCGImagePropertyTIFFImageDescription) \
    X(kCGImagePropertyTIFFMake) \
    X(kCGImagePropertyTIFFModel) \
    X(kCGImagePropertyTIFFOrientation) \
    X(kCGImagePropertyTIFFPhotometricInterpretation) \
    X(kCGImagePropertyTIFFPrimaryChromaticities) \
    X(kCGImagePropertyTIFFResolutionUnit) \
    X(kCGImagePropertyTIFFSoftware) \
    X(kCGImagePropertyTIFFTileLength) \
    X(kCGImagePropertyTIFFTileWidth) \
    X(kCGImagePropertyTIFFTransferFunction) \
    X(kCGImagePropertyTIFFWhitePoint) \
    X(kCGImagePropertyTIFFXResolution) \
    X(kCGImagePropertyTIFFYResolution) \
    X(kCGImageSourceCreateThumbnailFromImageAlways) \
    X(kCGImageSourceCreateThumbnailFromImageIfAbsent) \
    X(kCGImageSourceCreateThumbnailWithTransform) \
    X(kCGImageSourceShouldAllowFloat) \
    X(kCGImageSourceShouldCache) \
    X(kCGImageSourceShouldCacheImmediately) \
    X(kCGImageSourceSubsampleFactor) \
    X(kCGImageSourceThumbnailMaxPixelSize) \
    X(kCGImageSourceTypeIdentifierHint)

#define LC32_DECLARE_IMAGEIO_STRING_CONSTANT(name) \
    __typeof__(name) name = (__typeof__(name))(const void *) \
        &(LC32ConstantStringProxy){ \
            __CFConstantStringClassReference, 0x7c8, NULL, 0 \
        };
LC32_IMAGEIO_STRING_CONSTANTS(LC32_DECLARE_IMAGEIO_STRING_CONSTANT)
#undef LC32_DECLARE_IMAGEIO_STRING_CONSTANT

__attribute__((constructor))
static void LC32InitializeImageIOConstants(void) {
#define LC32_INITIALIZE_IMAGEIO_STRING_CONSTANT(name) LC32_CONST_STR_INIT(name);
    LC32_IMAGEIO_STRING_CONSTANTS(LC32_INITIALIZE_IMAGEIO_STRING_CONSTANT)
#undef LC32_INITIALIZE_IMAGEIO_STRING_CONSTANT
}

#undef LC32_IMAGEIO_STRING_CONSTANTS
