#!/bin/bash
# Generate an incrementally stable C header for the host startup log.
set -euo pipefail
export LC_ALL=C

fail() {
    printf 'build-info.sh: %s\n' "$1" >&2
    exit 1
}

root=
output=
while (( $# )); do
    case "$1" in
        --root|--output)
            (( $# >= 2 )) || fail "missing value for $1"
            if [[ $1 == --root ]]; then root=$2; else output=$2; fi
            shift 2
            ;;
        *) fail "unknown argument: $1" ;;
    esac
done
[[ -n $root && -n $output ]] || fail 'usage: --root PATH --output PATH'
[[ ! -d $output ]] || fail 'output must be a file, not a directory'
root=$(cd -- "$root" && pwd -P)

version=$(awk '/^Version:/ {
    sub(/^Version:[[:space:]]*/, ""); sub(/[[:space:]]*$/, ""); print; exit
}' "$root/control")
[[ $version =~ ^[0-9]+(\.[0-9]+){0,2}$ ]] ||
    fail 'control must contain a numeric Version (for example 0.0.1)'
bundle_id=$(plutil -extract CFBundleIdentifier raw -expect string -o - \
    "$root/HostFrameworks/LC32/Resources/Info.plist")

git_value() {
    git -C "$root" "$@" 2>/dev/null || true
}

commit=
branch=
# A source archive nested in another checkout must not inherit its identity.
if [[ $(git_value rev-parse --show-toplevel) == "$root" ]]; then
    commit=$(git_value rev-parse --short=7 HEAD)
    if [[ -n $commit && -n $(git_value status --porcelain --untracked-files=no) ]]; then
        commit+=-dirty
    fi
    branch=$(git_value symbolic-ref --quiet --short HEAD)
fi
commit=${commit:-unknown}
branch=${branch:-${GITHUB_HEAD_REF:-${GITHUB_REF_NAME:-}}}
if [[ -z $branch ]]; then
    if [[ $commit == unknown ]]; then branch=unknown; else branch=detached; fi
fi

c_string() {
    local value=$1 character code index
    printf '"'
    for (( index = 0; index < ${#value}; index++ )); do
        character=${value:index:1}
        case "$character" in
            \"|\\) printf '\\%s' "$character" ;;
            *)
                printf -v code '%d' "'$character"
                # Bash 3.2 can report UTF-8 bytes as signed char values.
                code=$(( code & 255 ))
                # Fixed-width octal cannot absorb following digits. Escape
                # '?' too, so CI metadata cannot introduce C trigraphs.
                if (( code < 32 || code == 127 || code == 63 )); then
                    printf '\\%03o' "$code"
                else
                    printf '%s' "$character"
                fi
                ;;
        esac
    done
    printf '"'
}

define() {
    printf '#define %s ' "$1"
    c_string "$2"
    printf '\n'
}

output_directory=$(dirname -- "$output")
mkdir -p -- "$output_directory"
temporary=$(mktemp "$output_directory/.LC32BuildInfo.XXXXXX")
trap 'rm -f -- "$temporary"' EXIT
trap 'exit 1' HUP INT TERM
{
    printf '// Generated by Scripts/build-info.sh; do not edit.\n#pragma once\n'
    define CONFIG_VERSION "$version"
    define CONFIG_SHARED_FRAMEWORK_BUNDLE_ID "$bundle_id"
    define CONFIG_COMMIT "$commit"
    define CONFIG_BRANCH "$branch"
} > "$temporary"

# Preserve both contents and mtime when metadata did not change. Replacing
# from the same directory keeps updates atomic for parallel builds.
if ! cmp -s -- "$temporary" "$output"; then
    mv -f -- "$temporary" "$output"
fi
